# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PopulationQuery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopulationQuery

  pod 'Bugsnag'

  target 'PopulationQueryTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OCMock', '~> 3.4'
  end

plugin 'cocoapods-keys', {
  :project => "PopulationQuery",
  :keys => [
    "BugsnagAPIKey"
  ]}

end
